FROM python:3.11

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o arquivo pyproject.toml e poetry.lock
COPY pyproject.toml poetry.lock ./

# Instalar o Poetry
RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-dev

# Copiar o restante do código da aplicação
COPY . .

# Expor a porta usada pela aplicação
EXPOSE 8000

# Comando para iniciar a aplicação
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
