services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    restart: always
    networks:
      - internal

  item-service:
    build:
      context: ./microservice-items
      dockerfile: Dockerfile
    container_name: item-service
    expose:
      - "8000"
    depends_on:
      - keycloak
    restart: always
    networks:
      - internal

  chipset-service:
    build:
      context: ./microservice-chipset
      dockerfile: Dockerfile
    container_name: chipset-service
    expose:
      - "8000"
    depends_on:
      - keycloak
    restart: always
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - item-service
      - chipset-service
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge
