version: "3.8"

services:
  pkd-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: pkd-keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: PKD-admin
      KEYCLOAK_ADMIN_PASSWORD: PKD-admin
    command: ["start-dev"]

  pkd-postgres:
    image: postgres:latest
    container_name: pkd-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  pkd-api:
    build: .
    container_name: pkd-api
    depends_on:
      - pkd-keycloak
      - pkd-postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
