version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    restart: always

  auth-service:
    build:
      context: ./microservice-auth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8001:8000"
    depends_on:
      - keycloak
    restart: always

  item-service:
    build:
      context: ./microservice-items
      dockerfile: Dockerfile
    container_name: item-service
    ports:
      - "8002:8000"
    depends_on:
      - auth-service
    restart: always

  chipset-service:
    build:
      context: ./microservice-chipset
      dockerfile: Dockerfile
    container_name: chipset-service
    ports:
      - "8003:8000"
    depends_on:
      - auth-service
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "8088:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro          
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # nginx.conf principal que inclui os outros
    depends_on:
      - auth-service
      - item-service
      - chipset-service
    restart: always
